[pytest]
pythonpath = .
addopts = -v --tb=short --maxfail=1
testpaths = tests
markers =
    integration: integration tests
    unit: unit tests
filterwarnings =
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning